### PR TITLE
add Palworld

### LINKED ISSUE #82: [Egg Request]: Palworld
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/1623730/Palworld/

### Links for the download

It uses SteamCMD to download. It's described in the installation docs linked below. Command: `steamcmd +login anonymous +app_update 2394010 validate +quit`

### Links for the install docs

https://tech.palworldgame.com/dedicated-server-guide#linux

### Does this app work on ARM?

No

### PR DESCRIPTION
**Pull request by QuintenQVD0**
### All Submissions:

closes #82 

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

### New Server Submissions:

1. [ ] Does your submission pass tests (server is connectable)?
2. [ ] Does your server use a custom docker image?
    * [ ] Have you tried to use a generic image?
    * [ ] Did you PR the necessary changes to make it work?
3. [x] Have you added the server to the main README.md?
4. [x] Have you added a unique README.md for the server you are adding?

### CODE REVIEW

**Comment by r3ps4J** [comment]
The egg doesn't work for me. See attached screenshot of the error.
image

**Comment by QuintenQVD0** [comment]
> The egg doesn't work for me. See attached screenshot of the error. (on Oracle ARM64, running Ubuntu 22.04 as host OS) image
> 
> This image works correctly on my server, perhaps it helps: https://github.com/nitrog0d/palworld-arm64

Did you ran the steamcmd setup script on the host?

**Comment by DarkSnakeX** [comment]
I want to test it, how much ram and disk did you put?

**Comment by r3ps4J** [comment]
Oh completely missed that, sorry! With the script it runs fine. One thing I noticed is that the variables are not actually replaced in the PalWorldSettings.ini, but I think it's meant to work that way looking at the PR for parkervcp/eggs.

**Comment by QuintenQVD0** [comment]
> Oh completely missed that, sorry! With the script it runs fine. One thing I noticed is that the variables are not actually replaced in the PalWorldSettings.ini, but I think it's meant to work that way looking at the PR for parkervcp/eggs.

If you are talking about the rcon then that will only happen on reinstall.

**Pull request merged**
