### PR TITLE
add egg-open-world.json

### LINKED ISSUE #15: [Egg Request]: Rimworld server (Open World mod)
### Does this expand an already existing service

No

### Link to a game or software

https://steamcommunity.com/sharedfiles/filedetails/?id=2768146099

### Links for the download

https://github.com/TastyLollipop/OpenWorld/releases/tag/1.4.0

### Links for the install docs

https://openworldhelp.fandom.com/wiki/Open_World_Wiki

### Does this app work on ARM?

Yes

### PR DESCRIPTION
**Pull request by QuintenQVD0**
closes #15

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@Redstylt Please test this egg.

**Comment by Redstylt** [comment]
The server is running ! When i try to connect i got an inbound traffic but in the game it doesn't connect.. "Connection timeout"

**Comment by Redstylt** [comment]
Also would be nice to have in variables:
```
Server Name: My Server Name
Server Description: My Server Description
```

**Comment by QuintenQVD0** [comment]
> The server is running ! When i try to connect i got an inbound traffic but in the game it doesn't connect.. "Connection timeout"

Is the port TCP and UDP open by default oracle is only TCP

**Comment by QuintenQVD0** [comment]
> Also would be nice to have in variables:
> 
> ```
> Server Name: My Server Name
> Server Description: My Server Description
> ```

Not realy posible as the game config is in .txt so you can not parce that easy. Just enter it manual in the config

**Pull request merged**
